# Crossover-docker minimal

FROM crossover:minimal
MAINTAINER Stanislav Ponomarev

USER root
RUN apt-get update -q -y && apt-get install \
    libasound2:i386 \
    libcapi20-3:i386 \
    libfontconfig1:i386 \
    libgsm1:i386 \
    libldap-2.4-2:i386 \
	libmpg123-0:i386 \
	libopenal1:i386 \
	libosmesa6:i386 \
	libsane:i386 \
	libtiff5:i386 \
	libv4l-0:i386 \
	libxcomposite1:i386 \
	libxinerama1:i386 \
	libxml2:i386 \
	libxslt1.1:i386 -q -y
