FROM 703915126451.dkr.ecr.us-east-2.amazonaws.com/starlab-virtue:virtue-crossover
MAINTAINER Stanislav Ponomarev

WORKDIR /home/virtue
USER virtue
RUN /opt/cxoffice/bin/cxbottle --create --description cmd --template win7 --bottle cmd
ENV APP_TO_RUN "/opt/cxoffice/bin/cxstart --bottle cmd --display :0 --new-console cmd.exe"
