sg_logstash:
  users:
    - logstash

sg_kibana_server:
  users:
    - kibanaserver

sg_kibana:
  users:
    - kibanaro

sg_all_access:
  users:
    - admin

sg_syslog_ng:
  users:
    - syslog-ng

sg_excalibur:
  users:
    - excalibur

sg_merlin:
  users:
    - merlin